### ISSUE TITLE
Error when importing files from 2023

### ISSUE THREAD

**Issue by bluestillidie00** [Stromberg90/football-manager-tools#1]
When trying to import manager clothing from FM23, the following error shows up
![image](https://user-images.githubusercontent.com/49170677/197512696-4edf77f2-61aa-4068-a81f-e3250cd3d447.png)

**Comment by Stromberg90** [comment]
Thanks for the report, I'll have a look when I get the time.

**Comment by Stromberg90** [comment]
This has now been fixed, thanks again for the report :)
