### ISSUE TITLE
Lightmaps in FM 2024

### ISSUE THREAD

**Issue by NautilusZaibatsu** [Stromberg90/football-manager-tools#2]
In the latest version of Football Manager there are lightmaps with the suffix [lm] for every interior room. The current version of this addon does not seem to import these and so the lightmap data is lost when exporting an edited .sia

**Comment by Stromberg90** [comment]
Thank you for filing a issue, I'll try look into this soon, should be pretty straight forward.

**Comment by Stromberg90** [comment]
I got a bit more work left, cleanup and such, but this should work so that you can progress in the meantime.
minimum blender version is now 4.
[io_scene_sia.zip](https://github.com/Stromberg90/football-manager-tools/files/13944010/io_scene_sia.zip)

**Comment by Stromberg90** [comment]
I added a new release now :)
